config:
  validation: true

build:
  maxIssues: 0
  excludeCorrectable: false

processors:
  active: true

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

style:
  MagicNumber:
    active: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: false
    excludes:
      - '/test/'
      - '/androidTest/'
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '100'
      - '1000'
  WildcardImport:
    active: true
  MaxLineLength:
    active: false

exceptions:
  SwallowedException:
    active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames: [ 'Throwable', 'Exception', 'RuntimeException' ]

empty-blocks:
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: '_|(ignore|expected).*'

potential-bugs:
  UnsafeCallOnNullableType:
    active: true # запрещаем '!!'
  LateinitUsage:
    active: false

complexity:
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

naming:
  PackageNaming:
    active: true
  TopLevelPropertyNaming:
    active: false
